SOCIAL_AUTH_TWITTER_KEY = 'KQc8kPCNUqvlxCU1oDDO9nvNP'
SOCIAL_AUTH_TWITTER_SECRET = '0m9SoyQGFDAcM2eKR9LfnqWk4BEwSZsneed7AEoILMqCqAdOCc'

SOCIAL_AUTH_LOGIN_REDIRECT_URL = '/home/'
SOCIAL_AUTH_LOGIN_URL = '/'
